### ISSUE TITLE
Missing detsets from observation in `ctx.get_meta` for satp1

### ISSUE THREAD

**Issue by jlashner** [simonsobs/sotodlib#656]
I'm looking into why det_cal info is failing in some books, and it seems like for some observations, after loading metadata with `ctx.load_meta`, the axis-manager is missing metadata for an entire wafer. 

obsid: `obs_1705319260_satp1_1111111`
context: `/so/metadata/satp1/contexts/smurf_detsets.yaml`

For example, the following code block prints the following
```python3
ctx_file = '/so/metadata/satp1/contexts/smurf_detsets.yaml'
ctx = Context(ctx_file)
obsid = 'obs_1705319260_satp1_1111111'
am = ctx.get_meta(obsid)

print(np.unique(am.det_info.detset))

>> array(['ufm_mv15_1704208082_tune', 'ufm_mv18_1704209412_tune',
       'ufm_mv22_1704210252_tune', 'ufm_mv29_1704208470_tune',
       'ufm_mv7_1704208122_tune', 'ufm_mv9_1704234303_tune'], dtype='<U24')
``` 
Notably, missing is a detset for Mv19, which is present in the book and the obsfiledb. I think it's possible this is why newer det_cal runs are failing.

**Comment by jlashner** [comment]
Diving a bit more into this, it seems like the expected detset for Mv19 (`ufm_mv19_1705079531_tune`) is not in the `smurf_detset_info` manifestdb: 
```
/so/metadata/satp1/manifests//smurf_detsets/smurf_detset_info_v0.sqlite
```

**Comment by kmharrington** [comment]
Is this fixed now that we've updated the databases?

**Comment by jlashner** [comment]
No... I'm currently running into the same issue and trying to debug.

**Comment by jlashner** [comment]
Ok so there's some strange behavior in metadata loading right now.... 

I'm trying to update my det-matching manifests for new sat1 :
```
from sotodlib.core import Context
import numpy as np

ctx = Context('context.yaml')
obsid = 'obs_1706143538_satp1_1111111'
am = ctx.get_meta(obsid)
print(np.unique(am.det_info.detset))
```

I get all 7 expected detsets:
```
['ufm_mv15_1704208082_tune' 'ufm_mv18_1704209412_tune'
 'ufm_mv19_1705079531_tune' 'ufm_mv22_1704210252_tune'
 'ufm_mv29_1704208470_tune' 'ufm_mv7_1704208122_tune'
 'ufm_mv9_1704234303_tune']
```
when I use the following context:
```
tags:
  basedir:  /so/metadata/satp1
  manifestdir: /so/metadata/satp1/manifests
imports:
  - sotodlib.io.load_book
  - sotodlib.io.metadata

obsfiledb: '{basedir}/obsfiledb.sqlite'
obsdb: '{basedir}/obsdb.sqlite'

obs_loader_type: 'obs-book'

metadata:
  - db: '{manifestdir}/smurf_detsets/v0/smurf_detset_info.sqlite'
    name: smurf
    det_info: true
  - db: '{manifestdir}/det_cal/v0/det_cal.sqlite'
    name: det_cal
  # - db: 'results/det_match.sqlite'
  #   name: det_match
  # - db: 'results/assignment.sqlite'
  #   name: det_assignment
```

However when I un-comment out my det-match metadata entries, the returned axismanager is missing all Mv19 detectors, since the Mv19 matching has not yet been added to my detset results.... it seems like these should not just be silently dropped.
