### ISSUE TITLE
Preprocess Gapfill

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#740]
We need an easy / simple way to replace into aman.signal instead of wrapping into gap_filled. There is a way in the function's implementation, need something in the preprocess module

**Comment by kmharrington** [comment]
Currently we have to do this. Where it's kind of annoying to have to have signal in 2 places

```
    - name: "glitchfill"
      signal: "signal"
      flag_aman: "jumps_twopi"
      flag: "jump_flag"
      process:
          nbuf: 10
          use_pca: False
          modes: 1
          wrap: "signal"
```
